from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem

from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from config import product

import time
import xml.etree.ElementTree as ET
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 575)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(650, 575))
        MainWindow.setMaximumSize(QtCore.QSize(650, 575))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 575))
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 0, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.itemFrame = QtWidgets.QFrame(self.centralwidget)
        self.itemFrame.setGeometry(QtCore.QRect(0, 20, 651, 291))
        self.itemFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.itemFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.itemFrame.setObjectName("itemFrame")
        self.formLayoutWidget = QtWidgets.QWidget(self.itemFrame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 221, 261))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.catLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.catLabel.setFont(font)
        self.catLabel.setObjectName("catLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.catLabel)
        self.catCbox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.catCbox.setAcceptDrops(True)
        self.catCbox.setObjectName("catCbox")
        self.catCbox.addItem("")
        self.catCbox.addItem("")
        self.catCbox.addItem("")
        self.catCbox.addItem("")
        self.catCbox.addItem("")
        self.catCbox.addItem("")
        self.catCbox.addItem("")
        self.catCbox.addItem("")
        self.catCbox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.catCbox)
        self.sizeLab = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sizeLab.setFont(font)
        self.sizeLab.setObjectName("sizeLab")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sizeLab)
        self.sizeCbox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.sizeCbox.setAcceptDrops(True)
        self.sizeCbox.setObjectName("sizeCbox")
        self.sizeCbox.addItem("")
        self.sizeCbox.addItem("")
        self.sizeCbox.addItem("")
        self.sizeCbox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sizeCbox)
        self.colorLab = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.colorLab.setFont(font)
        self.colorLab.setObjectName("colorLab")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.colorLab)
        self.ocolorLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ocolorLine.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ocolorLine.setFont(font)
        self.ocolorLine.setText("")
        self.ocolorLine.setObjectName("ocolorLine")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ocolorLine)
        self.keyLab = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.keyLab.setFont(font)
        self.keyLab.setObjectName("keyLab")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.keyLab)
        self.keyLine = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.keyLine.setEnabled(True)
        self.keyLine.setObjectName("keyLine")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.keyLine)
        self.addBut = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.addBut.setFont(font)
        self.addBut.setObjectName("addBut")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.addBut)
        self.deleteBut = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.deleteBut.setFont(font)
        self.deleteBut.setObjectName("deleteBut")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.deleteBut)
        self.colorCombo = QtWidgets.QComboBox(self.formLayoutWidget)
        self.colorCombo.setAcceptDrops(True)
        self.colorCombo.setObjectName("colorCombo")
        self.colorCombo.addItem("")
        self.colorCombo.addItem("")
        self.colorCombo.addItem("")
        self.colorCombo.addItem("")
        self.colorCombo.addItem("")
        self.colorCombo.addItem("")
        self.colorCombo.addItem("")
        self.colorCombo.addItem("")
        self.colorCombo.addItem("")
        self.colorCombo.addItem("")
        self.colorCombo.addItem("")
        self.colorCombo.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.colorCombo)
        self.tableWidget = QtWidgets.QTableWidget(self.itemFrame)
        self.tableWidget.setGeometry(QtCore.QRect(240, 10, 401, 275))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(401, 275))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        
        header = self.tableWidget.horizontalHeader()
        header.setFrameStyle(QtWidgets.QFrame.Box | QtWidgets.QFrame.Plain)
        header.setLineWidth(1)
        self.tableWidget.setHorizontalHeader(header)
        
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(17)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(20)
        self.bilFrame = QtWidgets.QFrame(self.centralwidget)
        self.bilFrame.setGeometry(QtCore.QRect(0, 310, 341, 191))
        self.bilFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bilFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bilFrame.setObjectName("bilFrame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.bilFrame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 321, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.nameLine = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.nameLine.setFont(font)
        self.nameLine.setInputMask("")
        self.nameLine.setText("")
        self.nameLine.setObjectName("nameLine")
        self.gridLayout.addWidget(self.nameLine, 0, 0, 1, 1)
        self.numberLine = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.numberLine.setFont(font)
        self.numberLine.setText("")
        self.numberLine.setObjectName("numberLine")
        self.gridLayout.addWidget(self.numberLine, 3, 0, 1, 1)
        self.emailLine = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.emailLine.setFont(font)
        self.emailLine.setText("")
        self.emailLine.setObjectName("emailLine")
        self.gridLayout.addWidget(self.emailLine, 2, 0, 1, 1)
        self.addressLine = QtWidgets.QLineEdit(self.bilFrame)
        self.addressLine.setGeometry(QtCore.QRect(10, 100, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addressLine.setFont(font)
        self.addressLine.setText("")
        self.addressLine.setObjectName("addressLine")
        self.aptLine = QtWidgets.QLineEdit(self.bilFrame)
        self.aptLine.setGeometry(QtCore.QRect(230, 100, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.aptLine.setFont(font)
        self.aptLine.setText("")
        self.aptLine.setObjectName("aptLine")
        self.zipLine = QtWidgets.QLineEdit(self.bilFrame)
        self.zipLine.setGeometry(QtCore.QRect(10, 130, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.zipLine.setFont(font)
        self.zipLine.setText("")
        self.zipLine.setObjectName("zipLine")
        self.stateCbox = QtWidgets.QComboBox(self.bilFrame)
        self.stateCbox.setGeometry(QtCore.QRect(200, 130, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.stateCbox.setFont(font)
        self.stateCbox.setObjectName("stateCbox")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.stateCbox.addItem("")
        self.countryCbox = QtWidgets.QComboBox(self.bilFrame)
        self.countryCbox.setGeometry(QtCore.QRect(258, 130, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.countryCbox.setFont(font)
        self.countryCbox.setObjectName("countryCbox")
        self.countryCbox.addItem("")
        self.countryCbox.addItem("")
        self.countryCbox.addItem("")
        self.cityLine = QtWidgets.QLineEdit(self.bilFrame)
        self.cityLine.setGeometry(QtCore.QRect(70, 130, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cityLine.setFont(font)
        self.cityLine.setText("")
        self.cityLine.setObjectName("cityLine")
        self.billLoadBut = QtWidgets.QPushButton(self.bilFrame)
        self.billLoadBut.setGeometry(QtCore.QRect(230, 160, 101, 23))
        self.billLoadBut.setObjectName("billLoadBut")
        self.ccFrame = QtWidgets.QFrame(self.centralwidget)
        self.ccFrame.setGeometry(QtCore.QRect(0, 500, 341, 71))
        self.ccFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ccFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ccFrame.setObjectName("ccFrame")
        self.ccnLine = QtWidgets.QLineEdit(self.ccFrame)
        self.ccnLine.setGeometry(QtCore.QRect(10, 10, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ccnLine.setFont(font)
        self.ccnLine.setText("")
        self.ccnLine.setObjectName("ccnLine")
        self.expmCbox = QtWidgets.QComboBox(self.ccFrame)
        self.expmCbox.setGeometry(QtCore.QRect(10, 40, 69, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.expmCbox.setFont(font)
        self.expmCbox.setObjectName("expmCbox")
        self.expmCbox.addItem("")
        self.expmCbox.addItem("")
        self.expmCbox.addItem("")
        self.expmCbox.addItem("")
        self.expmCbox.addItem("")
        self.expmCbox.addItem("")
        self.expmCbox.addItem("")
        self.expmCbox.addItem("")
        self.expmCbox.addItem("")
        self.expmCbox.addItem("")
        self.expmCbox.addItem("")
        self.expmCbox.addItem("")
        self.expyCbox = QtWidgets.QComboBox(self.ccFrame)
        self.expyCbox.setGeometry(QtCore.QRect(90, 40, 69, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.expyCbox.setFont(font)
        self.expyCbox.setObjectName("expyCbox")
        self.expyCbox.addItem("")
        self.expyCbox.addItem("")
        self.expyCbox.addItem("")
        self.expyCbox.addItem("")
        self.expyCbox.addItem("")
        self.expyCbox.addItem("")
        self.expyCbox.addItem("")
        self.expyCbox.addItem("")
        self.expyCbox.addItem("")
        self.expyCbox.addItem("")
        self.expyCbox.addItem("")
        self.cvvLine = QtWidgets.QLineEdit(self.ccFrame)
        self.cvvLine.setGeometry(QtCore.QRect(170, 40, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cvvLine.setFont(font)
        self.cvvLine.setText("")
        self.cvvLine.setObjectName("cvvLine")
        self.creLoadBut = QtWidgets.QPushButton(self.ccFrame)
        self.creLoadBut.setGeometry(QtCore.QRect(270, 40, 61, 23))
        self.creLoadBut.setObjectName("creLoadBut")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(340, 440, 311, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.startBut = QtWidgets.QPushButton(self.frame)
        self.startBut.setGeometry(QtCore.QRect(10, 10, 291, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.startBut.setFont(font)
        self.startBut.setObjectName("startBut")
        self.pauseBut = QtWidgets.QPushButton(self.frame)
        self.pauseBut.setEnabled(False)
        self.pauseBut.setGeometry(QtCore.QRect(10, 70, 131, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pauseBut.setFont(font)
        self.pauseBut.setObjectName("pauseBut")
        self.exitBut = QtWidgets.QPushButton(self.frame)
        self.exitBut.setGeometry(QtCore.QRect(150, 70, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exitBut.setFont(font)
        self.exitBut.setObjectName("exitBut")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        
        
        ###### Signal and Socket #####
        self.addBut.clicked.connect(self.addTolist)
        self.deleteBut.clicked.connect(self.removeFromlist)
        self.colorCombo.currentIndexChanged.connect(self.colorNotFound)
        
        self.exitBut.clicked.connect(MainWindow.close)
        
        self.startBut.clicked.connect(self.initial)
        self.startBut.clicked.connect(self.addToCart) 
        self.startBut.clicked.connect(self.fillout)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.catCbox, self.sizeCbox)
        MainWindow.setTabOrder(self.sizeCbox, self.ocolorLine)
        MainWindow.setTabOrder(self.ocolorLine, self.colorCombo)
        MainWindow.setTabOrder(self.colorCombo, self.keyLine)
        MainWindow.setTabOrder(self.keyLine, self.addBut)
        MainWindow.setTabOrder(self.addBut, self.deleteBut)
        MainWindow.setTabOrder(self.deleteBut, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.nameLine)
        MainWindow.setTabOrder(self.nameLine, self.emailLine)
        MainWindow.setTabOrder(self.emailLine, self.numberLine)
        MainWindow.setTabOrder(self.numberLine, self.addressLine)
        MainWindow.setTabOrder(self.addressLine, self.aptLine)
        MainWindow.setTabOrder(self.aptLine, self.zipLine)
        MainWindow.setTabOrder(self.zipLine, self.cityLine)
        MainWindow.setTabOrder(self.cityLine, self.stateCbox)
        MainWindow.setTabOrder(self.stateCbox, self.countryCbox)
        MainWindow.setTabOrder(self.countryCbox, self.billLoadBut)
        MainWindow.setTabOrder(self.billLoadBut, self.ccnLine)
        MainWindow.setTabOrder(self.ccnLine, self.expmCbox)
        MainWindow.setTabOrder(self.expmCbox, self.expyCbox)
        MainWindow.setTabOrder(self.expyCbox, self.cvvLine)
        MainWindow.setTabOrder(self.cvvLine, self.creLoadBut)
        MainWindow.setTabOrder(self.creLoadBut, self.startBut)
        MainWindow.setTabOrder(self.startBut, self.pauseBut)
        MainWindow.setTabOrder(self.pauseBut, self.exitBut)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Supreme Bot", "By Yeram Hwang"))
        self.label.setText(_translate("MainWindow", "Supreme Bot by Yeram Hwang"))
        self.catLabel.setText(_translate("MainWindow", "Category"))
        self.catCbox.setItemText(0, _translate("MainWindow", "Jackets"))
        self.catCbox.setItemText(1, _translate("MainWindow", "Shirts"))
        self.catCbox.setItemText(2, _translate("MainWindow", "Top/Sweater"))
        self.catCbox.setItemText(3, _translate("MainWindow", "Pants"))
        self.catCbox.setItemText(4, _translate("MainWindow", "Shorts"))
        self.catCbox.setItemText(5, _translate("MainWindow", "Hats"))
        self.catCbox.setItemText(6, _translate("MainWindow", "Bags"))
        self.catCbox.setItemText(7, _translate("MainWindow", "Acc"))
        self.catCbox.setItemText(8, _translate("MainWindow", "Skate"))
        self.sizeLab.setText(_translate("MainWindow", "Size"))
        self.sizeCbox.setItemText(0, _translate("MainWindow", "Small"))
        self.sizeCbox.setItemText(1, _translate("MainWindow", "Medium"))
        self.sizeCbox.setItemText(2, _translate("MainWindow", "Large"))
        self.sizeCbox.setItemText(3, _translate("MainWindow", "XLarge"))
        self.colorLab.setText(_translate("MainWindow", "Color"))
        self.ocolorLine.setPlaceholderText(_translate("MainWindow", "Enter Color if not listed."))
        self.keyLab.setText(_translate("MainWindow", "Key Word"))
        self.addBut.setText(_translate("MainWindow", "Add"))
        self.deleteBut.setText(_translate("MainWindow", "Remove"))
        self.colorCombo.setItemText(0, _translate("MainWindow", "Red"))
        self.colorCombo.setItemText(1, _translate("MainWindow", "Orange"))
        self.colorCombo.setItemText(2, _translate("MainWindow", "Yellow"))
        self.colorCombo.setItemText(3, _translate("MainWindow", "Green"))
        self.colorCombo.setItemText(4, _translate("MainWindow", "Blue"))
        self.colorCombo.setItemText(5, _translate("MainWindow", "Navy"))
        self.colorCombo.setItemText(6, _translate("MainWindow", "Purple"))
        self.colorCombo.setItemText(7, _translate("MainWindow", "Black"))
        self.colorCombo.setItemText(8, _translate("MainWindow", "White"))
        self.colorCombo.setItemText(9, _translate("MainWindow", "Tan"))
        self.colorCombo.setItemText(10, _translate("MainWindow", "Olive"))
        self.colorCombo.setItemText(11, _translate("MainWindow", "Others"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Category"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Color"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Key Word"))
        self.nameLine.setPlaceholderText(_translate("MainWindow", "Full Name (F+L)"))
        self.numberLine.setPlaceholderText(_translate("MainWindow", "Phone Number"))
        self.emailLine.setPlaceholderText(_translate("MainWindow", "Email"))
        self.addressLine.setPlaceholderText(_translate("MainWindow", "Address"))
        self.aptLine.setPlaceholderText(_translate("MainWindow", "APT#"))
        self.zipLine.setPlaceholderText(_translate("MainWindow", "ZIP"))
        self.stateCbox.setItemText(0, _translate("MainWindow", "AK"))
        self.stateCbox.setItemText(1, _translate("MainWindow", "AL"))
        self.stateCbox.setItemText(2, _translate("MainWindow", "AR"))
        self.stateCbox.setItemText(3, _translate("MainWindow", "AZ"))
        self.stateCbox.setItemText(4, _translate("MainWindow", "CA"))
        self.stateCbox.setItemText(5, _translate("MainWindow", "CO"))
        self.stateCbox.setItemText(6, _translate("MainWindow", "CT"))
        self.stateCbox.setItemText(7, _translate("MainWindow", "DE"))
        self.stateCbox.setItemText(8, _translate("MainWindow", "FL"))
        self.stateCbox.setItemText(9, _translate("MainWindow", "GA"))
        self.stateCbox.setItemText(10, _translate("MainWindow", "HI"))
        self.stateCbox.setItemText(11, _translate("MainWindow", "IA"))
        self.stateCbox.setItemText(12, _translate("MainWindow", "ID"))
        self.stateCbox.setItemText(13, _translate("MainWindow", "IL"))
        self.stateCbox.setItemText(14, _translate("MainWindow", "IN"))
        self.stateCbox.setItemText(15, _translate("MainWindow", "KS"))
        self.stateCbox.setItemText(16, _translate("MainWindow", "KY"))
        self.stateCbox.setItemText(17, _translate("MainWindow", "LA"))
        self.stateCbox.setItemText(18, _translate("MainWindow", "MA"))
        self.stateCbox.setItemText(19, _translate("MainWindow", "MD"))
        self.stateCbox.setItemText(20, _translate("MainWindow", "ME"))
        self.stateCbox.setItemText(21, _translate("MainWindow", "MI"))
        self.stateCbox.setItemText(22, _translate("MainWindow", "MN"))
        self.stateCbox.setItemText(23, _translate("MainWindow", "MO"))
        self.stateCbox.setItemText(24, _translate("MainWindow", "MS"))
        self.stateCbox.setItemText(25, _translate("MainWindow", "MT"))
        self.stateCbox.setItemText(26, _translate("MainWindow", "NC"))
        self.stateCbox.setItemText(27, _translate("MainWindow", "ND"))
        self.stateCbox.setItemText(28, _translate("MainWindow", "NE"))
        self.stateCbox.setItemText(29, _translate("MainWindow", "NH"))
        self.stateCbox.setItemText(30, _translate("MainWindow", "NJ"))
        self.stateCbox.setItemText(31, _translate("MainWindow", "NM"))
        self.stateCbox.setItemText(32, _translate("MainWindow", "NV"))
        self.stateCbox.setItemText(33, _translate("MainWindow", "NY"))
        self.stateCbox.setItemText(34, _translate("MainWindow", "OH"))
        self.stateCbox.setItemText(35, _translate("MainWindow", "OK"))
        self.stateCbox.setItemText(36, _translate("MainWindow", "OR"))
        self.stateCbox.setItemText(37, _translate("MainWindow", "PA"))
        self.stateCbox.setItemText(38, _translate("MainWindow", "RI"))
        self.stateCbox.setItemText(39, _translate("MainWindow", "SC"))
        self.stateCbox.setItemText(40, _translate("MainWindow", "SD"))
        self.stateCbox.setItemText(41, _translate("MainWindow", "TN"))
        self.stateCbox.setItemText(42, _translate("MainWindow", "TX"))
        self.stateCbox.setItemText(43, _translate("MainWindow", "UT"))
        self.stateCbox.setItemText(44, _translate("MainWindow", "VA"))
        self.stateCbox.setItemText(45, _translate("MainWindow", "VT"))
        self.stateCbox.setItemText(46, _translate("MainWindow", "WA"))
        self.stateCbox.setItemText(47, _translate("MainWindow", "WI"))
        self.stateCbox.setItemText(48, _translate("MainWindow", "WV"))
        self.stateCbox.setItemText(49, _translate("MainWindow", "WY"))
        self.countryCbox.setItemText(0, _translate("MainWindow", "USA"))
        self.countryCbox.setItemText(1, _translate("MainWindow", "Mexico"))
        self.countryCbox.setItemText(2, _translate("MainWindow", "Canada"))
        self.cityLine.setPlaceholderText(_translate("MainWindow", "City"))
        self.billLoadBut.setText(_translate("MainWindow", "Load"))
        self.ccnLine.setPlaceholderText(_translate("MainWindow", "Credit Card Number"))
        self.expmCbox.setItemText(0, _translate("MainWindow", "Jan"))
        self.expmCbox.setItemText(1, _translate("MainWindow", "Feb"))
        self.expmCbox.setItemText(2, _translate("MainWindow", "Mar"))
        self.expmCbox.setItemText(3, _translate("MainWindow", "Apr"))
        self.expmCbox.setItemText(4, _translate("MainWindow", "May"))
        self.expmCbox.setItemText(5, _translate("MainWindow", "Jun"))
        self.expmCbox.setItemText(6, _translate("MainWindow", "Jul"))
        self.expmCbox.setItemText(7, _translate("MainWindow", "Aug"))
        self.expmCbox.setItemText(8, _translate("MainWindow", "Sept"))
        self.expmCbox.setItemText(9, _translate("MainWindow", "Oct"))
        self.expmCbox.setItemText(10, _translate("MainWindow", "Nov"))
        self.expmCbox.setItemText(11, _translate("MainWindow", "Dec"))
        self.expyCbox.setItemText(0, _translate("MainWindow", "2020"))
        self.expyCbox.setItemText(1, _translate("MainWindow", "2021"))
        self.expyCbox.setItemText(2, _translate("MainWindow", "2022"))
        self.expyCbox.setItemText(3, _translate("MainWindow", "2023"))
        self.expyCbox.setItemText(4, _translate("MainWindow", "2024"))
        self.expyCbox.setItemText(5, _translate("MainWindow", "2025"))
        self.expyCbox.setItemText(6, _translate("MainWindow", "2026"))
        self.expyCbox.setItemText(7, _translate("MainWindow", "2027"))
        self.expyCbox.setItemText(8, _translate("MainWindow", "2028"))
        self.expyCbox.setItemText(9, _translate("MainWindow", "2029"))
        self.expyCbox.setItemText(10, _translate("MainWindow", "2030"))
        self.cvvLine.setPlaceholderText(_translate("MainWindow", "CVV"))
        self.creLoadBut.setText(_translate("MainWindow", "Load"))
        self.startBut.setText(_translate("MainWindow", "START!!!"))
        self.pauseBut.setText(_translate("MainWindow", "PAUSE"))
        self.exitBut.setText(_translate("MainWindow", "EXIT"))
        
    def initial(self, MainWindow):
        # load chrome
        global driver
        driver = webdriver.Chrome(ChromeDriverManager().install())

        # Goto Surpeme url
        driver.get('https://www.supremenewyork.com/shop/all')
       
        
    def addToCart(self, MainWindow):
        
        for i in range(self.tableWidget.rowCount()):
            # Category selection 
            cattext = self.tableWidget.item(i,0).text().lower()
            category = WebDriverWait(driver, 3).until(
                EC.presence_of_element_located((By.LINK_TEXT, cattext))
            )  
            category.click()
            
            # Product selection 
            keytext = self.tableWidget.item(i,3).text().capitalize()
            product = WebDriverWait(driver, 3).until(
                EC.presence_of_element_located((By.PARTIAL_LINK_TEXT, keytext))
            )  
            product.click()
            
            # Color selector
            driver.implicitly_wait(2)
            colortext = self.tableWidget.item(i,2).text()
            tempXpath = "//button[@data-style-name='" + colortext + "']"
            colorSel = driver.find_element_by_xpath(tempXpath)
            colorSel.click()
            
            # Size selector
            driver.implicitly_wait(1)
            sizetext = self.tableWidget.item(i,1).text()
            sizeXpath = "//*[@id='s']/option[. = '" + sizetext +  "']"
            size = driver.find_element_by_xpath(sizeXpath)
            size.click() 
            
            # Click add-to-cart button
            addtocartBut = WebDriverWait(driver, 3).until(
                EC.presence_of_element_located((By.NAME, "commit"))
            )
            addtocartBut.click()
            time.sleep(.5)
            
            # Navigate back to the listing page 
            driver.get('https://www.supremenewyork.com/shop/all')
        
    def fillout(self, MainWindow):
        # wait for checkout button element to load
        checkout = driver.find_element_by_xpath("//a[@class='button checkout']")
        checkout.click()
        
        # fill out checkout screen fields
        driver.find_element_by_id('order_billing_name').send_keys(self.nameLine.text())
        driver.find_element_by_id('order_email').send_keys(self.emailLine.text())
        driver.find_element_by_id('order_tel').send_keys(self.numberLine.text())
        driver.find_element_by_id('bo').send_keys(self.addressLine.text())
        driver.find_element_by_id('oba3').send_keys(self.aptLine.text())
        driver.find_element_by_id('order_billing_zip').send_keys(self.zipLine.text())
        driver.find_element_by_id('order_billing_city').send_keys(self.cityLine.text())
        
        driver.find_element_by_id('order_billing_state').send_keys(self.stateCbox.currentText())
        driver.find_element_by_id('order_billing_country').send_keys(self.countryCbox.currentText())

        # Credit Card info section
        tree = ET.parse('savedcinfo.xml')
        root = tree.getroot()
        
        driver.find_element_by_id('rnsnckrn').send_keys(self.ccnLine.text())
        driver.find_element_by_name('credit_card[month]').send_keys(self.expmCbox.currentText())
        driver.find_element_by_name('credit_card[year]').send_keys(self.expyCbox.currentText())
        driver.find_element_by_id('orcer').send_keys(self.cvvLine.text())

        # Process save address and term&condition check box click
        for combo in driver.find_elements_by_css_selector('.iCheck-helper'):
            combo.click()
        
        # Click process payment 
        driver.find_element_by_name('commit').click()

    def addTolist(self, MainWindow): 
        row = self.tableWidget.rowCount()
        self.tableWidget.insertRow(row)
        
        self.tableWidget.setItem(row, 0, QTableWidgetItem(self.catCbox.currentText()))
        self.tableWidget.setItem(row, 1, QTableWidgetItem(self.sizeCbox.currentText()))
        self.tableWidget.setItem(row, 2, QTableWidgetItem(self.colorCombo.currentText()))
        self.tableWidget.setItem(row, 3, QTableWidgetItem(self.keyLine.text()))
        
    def removeFromlist(self, MainWindow):
        self.tableWidget.removeRow(self.tableWidget.currentRow())
        
    def checkBlank():
        pass
        
    def colorNotFound(self, MainWindow):
        if(self.colorCombo.currentText() == 'Others'):
            self.ocolorLine.setEnabled(True)
        else:
            self.colorCombo.update()
            self.ocolorLine.setEnabled(False)
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())